; last updated by gen-error-codes on 2026-01-16 @ 02:08 UTC
PALETTE_RAM_BASE_EC            equ $01
EC_PALETTE_RAM_ADDRESS         equ $01 ; 000001
EC_PALETTE_RAM_DATA            equ $02 ; 000010
EC_PALETTE_RAM_MARCH           equ $03 ; 000011
EC_PALETTE_RAM_OUTPUT          equ $04 ; 000100
EC_PALETTE_RAM_WRITE           equ $05 ; 000101

K007121_RAM_BASE_EC            equ $06
EC_K007121_RAM_ADDRESS         equ $06 ; 000110
EC_K007121_RAM_DATA            equ $07 ; 000111
EC_K007121_RAM_MARCH           equ $08 ; 001000
EC_K007121_RAM_OUTPUT          equ $09 ; 001001
EC_K007121_RAM_WRITE           equ $0a ; 001010

WORK_RAM_BASE_EC               equ $0b
EC_WORK_RAM_ADDRESS            equ $0b ; 001011
EC_WORK_RAM_DATA               equ $0c ; 001100
EC_WORK_RAM_MARCH              equ $0d ; 001101
EC_WORK_RAM_OUTPUT             equ $0e ; 001110
EC_WORK_RAM_WRITE              equ $0f ; 001111
