all:
	make -f Makefile.1944
	make -f Makefile.19xx
	make -f Makefile.ddtod
	make -f Makefile.generic
	make -f Makefile.generic-tate
	make -f Makefile.vsavu
	make -f Makefile.xmcotaa

clean:
	make -f Makefile.1944 clean
	make -f Makefile.19xx clean
	make -f Makefile.ddtod clean
	make -f Makefile.generic clean
	make -f Makefile.generic-tate clean
	make -f Makefile.vsavu clean
	make -f Makefile.xmcotaa clean
