; These are tiles which are filled with a single
; color from the palette that we will use for the
; solid color blocks
TILE_B0_NUM		equ $31
TILE_B0_PAL_OFFSET	equ $2
TILE_B1_NUM		equ $32
TILE_B1_PAL_OFFSET	equ $4
TILE_B2_NUM		equ $33
TILE_B2_PAL_OFFSET	equ $6
TILE_B3_NUM		equ $34
TILE_B3_PAL_OFFSET	equ $8
TILE_B4_NUM		equ $35
TILE_B4_PAL_OFFSET	equ $a
TILE_BA_NUM		equ $36
TILE_BA_PAL_OFFSET	equ $c
