	include "cpu/z80/include/common.inc"
	include "cpu/z80/include/handlers/input_test.inc"

	global input_test

	section code

input_test:
		ld	de, d_screen_xys_list
		call	print_xy_string_list

		ld	hl, 0
		ld	(r_irq_count), hl

		ei

		ld	ix, d_input_test_list
		ld	iy, loop_cb
		call	input_test_handler

		di
		ret


loop_cb:
		SEEK_XY (SCREEN_START_X + 18), (SCREEN_START_Y + 3)
		ld	bc, (r_irq_count)
		RSUB	print_hex_word
		ret

	section data

	ifd _CONTROLLER_MAHJONG_

d_input_test_list:
	INPUT_TEST_ENTRY ($80 << 8 | IO_INPUT_P1)
	INPUT_TEST_ENTRY ($40 << 8 | IO_INPUT_P1)
	INPUT_TEST_ENTRY ($20 << 8 | IO_INPUT_P1)
	INPUT_TEST_ENTRY ($10 << 8 | IO_INPUT_P1)
	INPUT_TEST_ENTRY ($08 << 8 | IO_INPUT_P1)
	INPUT_TEST_ENTRY ($80 << 8 | IO_INPUT_P2)
	INPUT_TEST_ENTRY ($40 << 8 | IO_INPUT_P2)
	INPUT_TEST_ENTRY ($20 << 8 | IO_INPUT_P2)
	INPUT_TEST_ENTRY ($10 << 8 | IO_INPUT_P2)
	INPUT_TEST_ENTRY ($08 << 8 | IO_INPUT_P2)
	INPUT_TEST_ENTRY ($ff << 8 | IO_INPUT_SYS1)
	INPUT_TEST_ENTRY ($ff << 8 | IO_INPUT_SYS2)
	INPUT_TEST_LIST_END

d_screen_xys_list:
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 3), "P1C0"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 4), "P1C1"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 5), "P1C2"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 6), "P1C3"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 7), "P1C4"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 8), "P2C0"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 9), "P2C1"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 10), "P2C2"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 11), "P2C3"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 12), "P2C4"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 13), "SYS1"
	XY_STRING SCREEN_START_X, (SCREEN_START_Y + 14), "SYS2"

	XY_STRING (SCREEN_START_X + 14), (SCREEN_START_Y + 3), "IRQ"
	XY_STRING_LIST_END

	else

d_input_test_list:
	INPUT_TEST_ENTRY IO_INPUT_P1
	INPUT_TEST_ENTRY IO_INPUT_P2
	INPUT_TEST_ENTRY IO_INPUT_SYS1
	INPUT_TEST_ENTRY IO_INPUT_SYS2
	INPUT_TEST_LIST_END

d_screen_xys_list:
	XY_STRING (SCREEN_START_X + 2), (SCREEN_START_Y + 3), "P1"
	XY_STRING (SCREEN_START_X + 2), (SCREEN_START_Y + 4), "P2"
	XY_STRING (SCREEN_START_X + 0), (SCREEN_START_Y + 5), "SYS1"
	XY_STRING (SCREEN_START_X + 0), (SCREEN_START_Y + 6), "SYS2"

	XY_STRING (SCREEN_START_X + 14), (SCREEN_START_Y + 3), "IRQ"
	XY_STRING_LIST_END

	endif
