	include "cpu/68000/error_codes.inc"
	include "cpu/68000/macros.inc"
	include "cpu/68000/print_error.inc"
	include "cpu/68000/handlers/error.inc"

	include "error_codes.inc"

	global EC_LIST

	section data

EC_LIST:
	EC_ENTRY WORK_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY PALETTE_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY PALETTE_EXT_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_EXT_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_EXT_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_EXT_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_EXT_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_EXT_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_EXT_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_EXT_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_EXT_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_EXT_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_EXT_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_EXT_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_EXT_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY SPRITE_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY DIAG_ROM_CRC32, PRINT_ERROR_CRC32
	EC_ENTRY DIAG_ROM_ADDRESS, PRINT_ERROR_HEX_BYTE
	EC_LIST_END

STR_WORK_RAM_ADDRESS:			STRING "WORK RAM ADDRESS"
STR_WORK_RAM_DATA_LOWER:		STRING "WORK RAM DATA (LOWER)"
STR_WORK_RAM_DATA_UPPER:		STRING "WORK RAM DATA (UPPER)"
STR_WORK_RAM_DATA_BOTH:			STRING "WORK RAM DATA (BOTH)"
STR_WORK_RAM_MARCH_LOWER:		STRING "WORK RAM MARCH (LOWER)"
STR_WORK_RAM_MARCH_UPPER:		STRING "WORK RAM MARCH (UPPER)"
STR_WORK_RAM_MARCH_BOTH:		STRING "WORK RAM MARCH (BOTH)"
STR_WORK_RAM_OUTPUT_LOWER:		STRING "WORK RAM DEAD OUTPUT (LOWER)"
STR_WORK_RAM_OUTPUT_UPPER:		STRING "WORK RAM DEAD OUTPUT (UPPER)"
STR_WORK_RAM_OUTPUT_BOTH:		STRING "WORK RAM DEAD OUTPUT (BOTH)"
STR_WORK_RAM_WRITE_LOWER:		STRING "WORK RAM WRITE (LOWER)"
STR_WORK_RAM_WRITE_UPPER:		STRING "WORK RAM WRITE (UPPER)"
STR_WORK_RAM_WRITE_BOTH:		STRING "WORK RAM WRITE (BOTH)"

STR_PALETTE_RAM_ADDRESS:		STRING "PALETTE RAM ADDRESS"
STR_PALETTE_RAM_DATA_LOWER:		STRING "PALETTE RAM DATA (LOWER)"
STR_PALETTE_RAM_DATA_UPPER:		STRING "PALETTE RAM DATA (UPPER)"
STR_PALETTE_RAM_DATA_BOTH:		STRING "PALETTE RAM DATA (BOTH)"
STR_PALETTE_RAM_MARCH_LOWER:		STRING "PALETTE RAM MARCH (LOWER)"
STR_PALETTE_RAM_MARCH_UPPER:		STRING "PALETTE RAM MARCH (UPPER)"
STR_PALETTE_RAM_MARCH_BOTH:		STRING "PALETTE RAM MARCH (BOTH)"
STR_PALETTE_RAM_OUTPUT_LOWER:		STRING "PALETTE RAM DEAD OUTPUT (LOWER)"
STR_PALETTE_RAM_OUTPUT_UPPER:		STRING "PALETTE RAM DEAD OUTPUT (UPPER)"
STR_PALETTE_RAM_OUTPUT_BOTH:		STRING "PALETTE RAM DEAD OUTPUT (BOTH)"
STR_PALETTE_RAM_WRITE_LOWER:		STRING "PALETTE RAM WRITE (LOWER)"
STR_PALETTE_RAM_WRITE_UPPER:		STRING "PALETTE RAM WRITE (UPPER)"
STR_PALETTE_RAM_WRITE_BOTH:		STRING "PALETTE RAM WRITE (BOTH)"

STR_PALETTE_EXT_RAM_ADDRESS:		STRING "PAL EXT RAM ADDRESS"
STR_PALETTE_EXT_RAM_DATA_LOWER:		STRING "PAL EXT RAM DATA (LOWER)"
STR_PALETTE_EXT_RAM_DATA_UPPER:		STRING "PAL EXT RAM DATA (UPPER)"
STR_PALETTE_EXT_RAM_DATA_BOTH:		STRING "PAL EXT RAM DATA (BOTH)"
STR_PALETTE_EXT_RAM_MARCH_LOWER:	STRING "PAL EXT RAM MARCH (LOWER)"
STR_PALETTE_EXT_RAM_MARCH_UPPER:	STRING "PAL EXT RAM MARCH (UPPER)"
STR_PALETTE_EXT_RAM_MARCH_BOTH:		STRING "PAL EXT RAM MARCH (BOTH)"
STR_PALETTE_EXT_RAM_OUTPUT_LOWER:	STRING "PAL EXT RAM DEAD OUTPUT (LOWER)"
STR_PALETTE_EXT_RAM_OUTPUT_UPPER:	STRING "PAL EXT RAM DEAD OUTPUT (UPPER)"
STR_PALETTE_EXT_RAM_OUTPUT_BOTH:	STRING "PAL EXT RAM DEAD OUTPUT (BOTH)"
STR_PALETTE_EXT_RAM_WRITE_LOWER:	STRING "PAL EXT RAM WRITE (LOWER)"
STR_PALETTE_EXT_RAM_WRITE_UPPER:	STRING "PAL EXT RAM WRITE (UPPER)"
STR_PALETTE_EXT_RAM_WRITE_BOTH:		STRING "PAL EXT RAM WRITE (BOTH)"

STR_SPRITE_RAM_ADDRESS:			STRING "PAL EXT RAM ADDRESS"
STR_SPRITE_RAM_DATA_LOWER:		STRING "PAL EXT RAM DATA (LOWER)"
STR_SPRITE_RAM_DATA_UPPER:		STRING "PAL EXT RAM DATA (UPPER)"
STR_SPRITE_RAM_DATA_BOTH:		STRING "PAL EXT RAM DATA (BOTH)"
STR_SPRITE_RAM_MARCH_LOWER:		STRING "PAL EXT RAM MARCH (LOWER)"
STR_SPRITE_RAM_MARCH_UPPER:		STRING "PAL EXT RAM MARCH (UPPER)"
STR_SPRITE_RAM_MARCH_BOTH:		STRING "PAL EXT RAM MARCH (BOTH)"
STR_SPRITE_RAM_OUTPUT_LOWER:		STRING "PAL EXT RAM DEAD OUTPUT (LOWER)"
STR_SPRITE_RAM_OUTPUT_UPPER:		STRING "PAL EXT RAM DEAD OUTPUT (UPPER)"
STR_SPRITE_RAM_OUTPUT_BOTH:		STRING "PAL EXT RAM DEAD OUTPUT (BOTH)"
STR_SPRITE_RAM_WRITE_LOWER:		STRING "PAL EXT RAM WRITE (LOWER)"
STR_SPRITE_RAM_WRITE_UPPER:		STRING "PAL EXT RAM WRITE (UPPER)"
STR_SPRITE_RAM_WRITE_BOTH:		STRING "PAL EXT RAM WRITE (BOTH)"

STR_DIAG_ROM_CRC32:			STRING "DIAG ROM CRC32 ERROR"
STR_DIAG_ROM_ADDRESS:			STRING "DIAG ROM ADDRESS ERROR"
