	include "cpu/68000/macros.inc"
	include "cpu/68000/tests/auto.inc"

	global AUTO_DSUB_LIST
	global AUTO_FUNC_LIST

	section data

AUTO_DSUB_LIST:
	AUTO_ENTRY auto_diag_rom_address_test_dsub, STR_TESTING_DIAG_ROM_ADDRESS
	AUTO_ENTRY auto_diag_rom_crc32_test_dsub, STR_TESTING_DIAG_ROM_CRC32
	AUTO_ENTRY auto_work_ram_tests_dsub, STR_TESTING_WORK_RAM
	AUTO_LIST_END

AUTO_FUNC_LIST:
	AUTO_ENTRY auto_fg_sprite_ram_tests, STR_TESTING_FG_SPRITE_RAM
	AUTO_LIST_END

STR_TESTING_DIAG_ROM_ADDRESS:	STRING "TESTING DIAG ROM ADDRESS"
STR_TESTING_DIAG_ROM_CRC32:	STRING "TESTING DIAG ROM CRC32"
STR_TESTING_FG_SPRITE_RAM:	STRING "TESTING FG/SPRITE RAM"
STR_TESTING_WORK_RAM:		STRING "TESTING WORK RAM"
