all:
	make -f Makefile.baddudes-hardware
	make -f Makefile.baddudes-mame
	make -f Makefile.hbarrel-hardware
	make -f Makefile.hbarrel-mame
	make -f Makefile.hippodrm-hardware
	make -f Makefile.hippodrm-mame
	make -f Makefile.robocop-hardware
	make -f Makefile.robocop-mame

clean:
	make -f Makefile.baddudes-hardware clean
	make -f Makefile.baddudes-mame clean
	make -f Makefile.hbarrel-hardware clean
	make -f Makefile.hbarrel-mame clean
	make -f Makefile.hippodrm-hardware clean
	make -f Makefile.hippodrm-mame clean
	make -f Makefile.robocop-hardware clean
	make -f Makefile.robocop-mame clean
