	include "cpu/6309/include/error_codes.inc"
	include "cpu/6309/include/macros.inc"
	include "cpu/6309/include/print_error.inc"
	include "cpu/6309/include/handlers/error.inc"

	include "error_codes.inc"

	global EC_LIST

	section data

EC_LIST:
	EC_ENTRY PALETTE_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_DATA, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_MARCH, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_OUTPUT, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_WRITE, PRINT_ERROR_ADDRESS
	EC_LIST_END


STR_PALETTE_RAM_ADDRESS:	STRING "PALETTE RAM ADDRESS"
STR_PALETTE_RAM_DATA:		STRING "PALETTE RAM DATA"
STR_PALETTE_RAM_MARCH:		STRING "PALETTE RAM MARCH"
STR_PALETTE_RAM_OUTPUT:		STRING "PALETTE RAM DEAD OUTPUT"
STR_PALETTE_RAM_WRITE:		STRING "PALETTE RAM WRITE"

