; These are tiles which are filled with a single
; color from the palette that we will use for the
; solid color blocks
TILE_B0_NUM		equ $f00003
TILE_B0_PAL_OFFSET	equ $1e
TILE_B1_NUM		equ $630004
TILE_B1_PAL_OFFSET	equ $e
TILE_B2_NUM		equ $8b0007
TILE_B2_PAL_OFFSET	equ $2
TILE_B3_NUM		equ $3d0009
TILE_B3_PAL_OFFSET	equ $6
TILE_BA_NUM		equ $08000b	; bit all
TILE_BA_PAL_OFFSET1	equ $4
TILE_BA_PAL_OFFSET2	equ $10
