	include "cpu/68000/include/macros.inc"
	include "cpu/68000/include/tests/auto.inc"

	global AUTO_DSUB_LIST
	global AUTO_FUNC_LIST

	section data

AUTO_DSUB_LIST:
	AUTO_ENTRY auto_mad_rom_address_test_dsub, STR_TESTING_MAD_ROM_ADDRESS
	AUTO_ENTRY auto_mad_rom_crc32_test_dsub, STR_TESTING_MAD_ROM_CRC32
	AUTO_ENTRY auto_work_ram_tests_dsub, STR_TESTING_WORK_RAM
	AUTO_LIST_END

AUTO_FUNC_LIST:
	AUTO_ENTRY auto_palette_ram_tests, STR_TESTING_PALETTE_RAM
	AUTO_LIST_END

STR_TESTING_MAD_ROM_ADDRESS:	STRING "TESTING MAD ROM ADDRESS"
STR_TESTING_MAD_ROM_CRC32:	STRING "TESTING MAD ROM CRC32"
STR_TESTING_PALETTE_RAM:	STRING "TESTING PALETTE RAM"
STR_TESTING_WORK_RAM:		STRING "TESTING WORK RAM"
