all:
	make -f Makefile.skysoldr-hardware
	make -f Makefile.skysoldr-mame
	make -f	Makefile.timesold-hardware
	make -f Makefile.timesold-mame

clean:
	make -f Makefile.skysoldr-hardware clean
	make -f Makefile.skysoldr-mame clean
	make -f	Makefile.timesold-hardware clean
	make -f Makefile.timesold-mame clean
