; last updated by gen-error-codes on 2025-03-21 @ 21:11 UTC
PALETTE_RAM_BASE_EC            equ $01
EC_PALETTE_RAM_ADDRESS         equ $01 ; 000001
EC_PALETTE_RAM_DATA            equ $02 ; 000010
EC_PALETTE_RAM_MARCH           equ $03 ; 000011
EC_PALETTE_RAM_OUTPUT          equ $04 ; 000100
EC_PALETTE_RAM_WRITE           equ $05 ; 000101

SPRITE1_RAM_BASE_EC            equ $06
EC_SPRITE1_RAM_ADDRESS         equ $06 ; 000110
EC_SPRITE1_RAM_DATA            equ $07 ; 000111
EC_SPRITE1_RAM_MARCH           equ $08 ; 001000
EC_SPRITE1_RAM_OUTPUT          equ $09 ; 001001
EC_SPRITE1_RAM_WRITE           equ $0a ; 001010

SPRITE2_RAM_BASE_EC            equ $0b
EC_SPRITE2_RAM_ADDRESS         equ $0b ; 001011
EC_SPRITE2_RAM_DATA            equ $0c ; 001100
EC_SPRITE2_RAM_MARCH           equ $0d ; 001101
EC_SPRITE2_RAM_OUTPUT          equ $0e ; 001110
EC_SPRITE2_RAM_WRITE           equ $0f ; 001111

TILE1_RAM_BASE_EC              equ $10
EC_TILE1_RAM_ADDRESS           equ $10 ; 010000
EC_TILE1_RAM_DATA              equ $11 ; 010001
EC_TILE1_RAM_MARCH             equ $12 ; 010010
EC_TILE1_RAM_OUTPUT            equ $13 ; 010011
EC_TILE1_RAM_WRITE             equ $14 ; 010100

TILE2_RAM_BASE_EC              equ $15
EC_TILE2_RAM_ADDRESS           equ $15 ; 010101
EC_TILE2_RAM_DATA              equ $16 ; 010110
EC_TILE2_RAM_MARCH             equ $17 ; 010111
EC_TILE2_RAM_OUTPUT            equ $18 ; 011000
EC_TILE2_RAM_WRITE             equ $19 ; 011001

TILE3_RAM_BASE_EC              equ $1a
EC_TILE3_RAM_ADDRESS           equ $1a ; 011010
EC_TILE3_RAM_DATA              equ $1b ; 011011
EC_TILE3_RAM_MARCH             equ $1c ; 011100
EC_TILE3_RAM_OUTPUT            equ $1d ; 011101
EC_TILE3_RAM_WRITE             equ $1e ; 011110

WORK_RAM_BASE_EC               equ $1f
EC_WORK_RAM_ADDRESS            equ $1f ; 011111
EC_WORK_RAM_DATA               equ $20 ; 100000
EC_WORK_RAM_MARCH              equ $21 ; 100001
EC_WORK_RAM_OUTPUT             equ $22 ; 100010
EC_WORK_RAM_WRITE              equ $23 ; 100011
