	include "cpu/68000/error_codes.inc"
	include "cpu/68000/macros.inc"
	include "cpu/68000/print_error.inc"
	include "cpu/68000/handlers/error.inc"

	include "error_codes.inc"

	global EC_LIST

	section data

EC_LIST:
	EC_ENTRY RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY DIAG_ROM_CRC32, PRINT_ERROR_CRC32
	EC_ENTRY DIAG_ROM_ADDRESS, PRINT_ERROR_HEX_BYTE
	EC_LIST_END

STR_RAM_ADDRESS:		STRING "RAM ADDRESS"

STR_RAM_DATA_LOWER:		STRING "RAM DATA (LOWER)"
STR_RAM_DATA_UPPER:		STRING "RAM DATA (UPPER)"
STR_RAM_DATA_BOTH:		STRING "RAM DATA (BOTH)"

STR_RAM_MARCH_LOWER:		STRING "RAM MARCH (LOWER)"
STR_RAM_MARCH_UPPER:		STRING "RAM MARCH (UPPER)"
STR_RAM_MARCH_BOTH:		STRING "RAM MARCH (BOTH)"

STR_RAM_OUTPUT_LOWER:		STRING "RAM DEAD OUTPUT (LOWER)"
STR_RAM_OUTPUT_UPPER:		STRING "RAM DEAD OUTPUT (UPPER)"
STR_RAM_OUTPUT_BOTH:		STRING "RAM DEAD OUTPUT (BOTH)"

STR_RAM_WRITE_LOWER:		STRING "RAM WRITE (LOWER)"
STR_RAM_WRITE_UPPER:		STRING "RAM WRITE (UPPER)"
STR_RAM_WRITE_BOTH:		STRING "RAM WRITE (BOTH)"

STR_DIAG_ROM_CRC32:		STRING "DIAG ROM CRC32 ERROR"
STR_DIAG_ROM_ADDRESS:		STRING "DIAG ROM ADDRESS ERROR"
