	include "cpu/68000/error_codes.inc"
	include "cpu/68000/error_handler.inc"
	include "cpu/68000/macros.inc"
	include "cpu/68000/print_error.inc"

	include "error_codes.inc"

	global EC_TABLE
	global EC_PRINT_TABLE

	section data

EC_TABLE:
	EC_ENTRY RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY DIAG_ROM_CRC32, PRINT_ERROR_CRC32
	EC_ENTRY DIAG_ROM_ADDRESS, PRINT_ERROR_HEX_BYTE
	EC_ENTRY_NULL

EC_PRINT_TABLE:
	EC_PRINT_ENTRY PRINT_ERROR_ADDRESS, print_error_address_dsub
	EC_PRINT_ENTRY PRINT_ERROR_CRC32, print_error_crc32_dsub
	EC_PRINT_ENTRY PRINT_ERROR_HEX_BYTE, print_error_hex_byte_dsub
	EC_PRINT_ENTRY PRINT_ERROR_MEMORY, print_error_memory_override_dsub
	EC_PRINT_ENTRY PRINT_ERROR_STRING, print_error_string_dsub
	EC_PRINT_ENTRY_NULL

STR_RAM_ADDRESS:		STRING "RAM ADDRESS"

STR_RAM_DATA_LOWER:		STRING "RAM DATA (LOWER)"
STR_RAM_DATA_UPPER:		STRING "RAM DATA (UPPER)"
STR_RAM_DATA_BOTH:		STRING "RAM DATA (BOTH)"

STR_RAM_OUTPUT_LOWER:		STRING "RAM DEAD OUTPUT (LOWER)"
STR_RAM_OUTPUT_UPPER:		STRING "RAM DEAD OUTPUT (UPPER)"
STR_RAM_OUTPUT_BOTH:		STRING "RAM DEAD OUTPUT (BOTH)"

STR_RAM_WRITE_LOWER:		STRING "RAM WRITE (LOWER)"
STR_RAM_WRITE_UPPER:		STRING "RAM WRITE (UPPER)"
STR_RAM_WRITE_BOTH:		STRING "RAM WRITE (BOTH)"

STR_DIAG_ROM_CRC32:		STRING "DIAG ROM CRC32 ERROR"
STR_DIAG_ROM_ADDRESS:		STRING "DIAG ROM ADDRESS ERROR"
