	include "cpu/68000/include/error_codes.inc"
	include "cpu/68000/include/macros.inc"
	include "cpu/68000/include/print_error.inc"
	include "cpu/68000/include/handlers/error.inc"

	include "error_codes.inc"

	global EC_LIST

	section data

EC_LIST:
	EC_ENTRY WORK_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY PALETTE_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY SPRITE_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_DATA, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_MARCH, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_OUTPUT, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_WRITE, PRINT_ERROR_ADDRESS

	EC_ENTRY TILE_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY TILE_RAM_DATA, PRINT_ERROR_MEMORY
	EC_ENTRY TILE_RAM_MARCH, PRINT_ERROR_MEMORY
	EC_ENTRY TILE_RAM_OUTPUT, PRINT_ERROR_ADDRESS
	EC_ENTRY TILE_RAM_WRITE, PRINT_ERROR_ADDRESS

	EC_ENTRY MAD_ROM_CRC32, PRINT_ERROR_CRC32
	EC_ENTRY MAD_ROM_ADDRESS, PRINT_ERROR_HEX_BYTE
	EC_LIST_END

; This game has a rotated screen which limits the available
; width.  Some error below are shortened compared to what is
; normally used.
STR_WORK_RAM_ADDRESS:		STRING "WORK RAM ADDRESS"

STR_WORK_RAM_DATA_LOWER:	STRING "WORK RAM DATA (LOWER)"
STR_WORK_RAM_DATA_UPPER:	STRING "WORK RAM DATA (UPPER)"
STR_WORK_RAM_DATA_BOTH:		STRING "WORK RAM DATA (BOTH)"

STR_WORK_RAM_MARCH_LOWER:	STRING "WORK RAM MARCH (LOWER)"
STR_WORK_RAM_MARCH_UPPER:	STRING "WORK RAM MARCH (UPPER)"
STR_WORK_RAM_MARCH_BOTH:	STRING "WORK RAM MARCH (BOTH)"

STR_WORK_RAM_OUTPUT_LOWER:	STRING "WORK RAM OUTPUT (LOWER)"
STR_WORK_RAM_OUTPUT_UPPER:	STRING "WORK RAM OUTPUT (UPPER)"
STR_WORK_RAM_OUTPUT_BOTH:	STRING "WORK RAM OUTPUT (BOTH)"

STR_WORK_RAM_WRITE_LOWER:	STRING "WORK RAM WRITE (LOWER)"
STR_WORK_RAM_WRITE_UPPER:	STRING "WORK RAM WRITE (UPPER)"
STR_WORK_RAM_WRITE_BOTH:	STRING "WORK RAM WRITE (BOTH)"

STR_PALETTE_RAM_ADDRESS:	STRING "PAL RAM ADDRESS"

STR_PALETTE_RAM_DATA_LOWER:	STRING "PAL RAM DATA (LOWER)"
STR_PALETTE_RAM_DATA_UPPER:	STRING "PAL RAM DATA (UPPER)"
STR_PALETTE_RAM_DATA_BOTH:	STRING "PAL RAM DATA (BOTH)"

STR_PALETTE_RAM_MARCH_LOWER:	STRING "PAL RAM MARCH (LOWER)"
STR_PALETTE_RAM_MARCH_UPPER:	STRING "PAL RAM MARCH (UPPER)"
STR_PALETTE_RAM_MARCH_BOTH:	STRING "PAL RAM MARCH (BOTH)"

STR_PALETTE_RAM_OUTPUT_LOWER:	STRING "PAL RAM OUTPUT (LOWER)"
STR_PALETTE_RAM_OUTPUT_UPPER:	STRING "PAL RAM OUTPUT (UPPER)"
STR_PALETTE_RAM_OUTPUT_BOTH:	STRING "PAL RAM OUTPUT (BOTH)"

STR_PALETTE_RAM_WRITE_LOWER:	STRING "PAL RAM WRITE (LOWER)"
STR_PALETTE_RAM_WRITE_UPPER:	STRING "PAL RAM WRITE (UPPER)"
STR_PALETTE_RAM_WRITE_BOTH:	STRING "PAL RAM WRITE (BOTH)"

STR_SPRITE_RAM_ADDRESS:		STRING "SPRITE RAM ADDRESS"
STR_SPRITE_RAM_DATA:		STRING "SPRITE RAM DATA"
STR_SPRITE_RAM_MARCH:		STRING "SPRITE RAM MARCH"
STR_SPRITE_RAM_OUTPUT:		STRING "SPRITE RAM OUTPUT"
STR_SPRITE_RAM_WRITE:		STRING "SPRITE RAM WRITE"

STR_TILE_RAM_ADDRESS:		STRING "TILE RAM ADDRESS"
STR_TILE_RAM_DATA:		STRING "TILE RAM DATA"
STR_TILE_RAM_MARCH:		STRING "TILE RAM MARCH"
STR_TILE_RAM_OUTPUT:		STRING "TILE RAM OUTPUT"
STR_TILE_RAM_WRITE:		STRING "TILE RAM WRITE"

STR_MAD_ROM_CRC32:		STRING "MAD ROM CRC32 ERROR"
STR_MAD_ROM_ADDRESS:		STRING "MAD ROM ADDRESS ERROR"
