	include "cpu/68000/include/error_codes.inc"
	include "cpu/68000/include/macros.inc"
	include "cpu/68000/include/print_error.inc"
	include "cpu/68000/include/handlers/error.inc"

	include "error_codes.inc"

	global EC_LIST

	section data

EC_LIST:
	EC_ENTRY BG_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY BG_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY BG_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY BG_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY BG_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY BG_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY BG_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY BG_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY BG_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY BG_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY BG_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY BG_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY BG_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY FG_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY FG_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY FG_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY FG_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY FG_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY FG_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY FG_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY FG_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY FG_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY FG_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY FG_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY FG_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY FG_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY PALETTE_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY PALETTE_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY PALETTE_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY SPRITE_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY SPRITE_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY SPRITE_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY TXT_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY TXT_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY TXT_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY TXT_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY TXT_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY TXT_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY TXT_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY TXT_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY TXT_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY TXT_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY TXT_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY TXT_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY TXT_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS

	EC_ENTRY WORK_RAM_ADDRESS, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_DATA_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_DATA_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_DATA_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_MARCH_LOWER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_MARCH_UPPER, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_MARCH_BOTH, PRINT_ERROR_MEMORY
	EC_ENTRY WORK_RAM_OUTPUT_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_OUTPUT_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_OUTPUT_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_WRITE_LOWER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_WRITE_UPPER, PRINT_ERROR_ADDRESS
	EC_ENTRY WORK_RAM_WRITE_BOTH, PRINT_ERROR_ADDRESS
	EC_ENTRY MAD_ROM_CRC32, PRINT_ERROR_CRC32
	EC_ENTRY MAD_ROM_ADDRESS, PRINT_ERROR_HEX_BYTE
	EC_LIST_END

STR_BG_RAM_ADDRESS:		STRING "BG RAM ADDRESS"
STR_BG_RAM_DATA_LOWER:		STRING "BG RAM DATA (LOWER)"
STR_BG_RAM_DATA_UPPER:		STRING "BG RAM DATA (UPPER)"
STR_BG_RAM_DATA_BOTH:		STRING "BG RAM DATA (BOTH)"
STR_BG_RAM_MARCH_LOWER:		STRING "BG RAM MARCH (LOWER)"
STR_BG_RAM_MARCH_UPPER:		STRING "BG RAM MARCH (UPPER)"
STR_BG_RAM_MARCH_BOTH:		STRING "BG RAM MARCH (BOTH)"
STR_BG_RAM_OUTPUT_LOWER:	STRING "BG RAM DEAD OUTPUT (LOWER)"
STR_BG_RAM_OUTPUT_UPPER:	STRING "BG RAM DEAD OUTPUT (UPPER)"
STR_BG_RAM_OUTPUT_BOTH:		STRING "BG RAM DEAD OUTPUT (BOTH)"
STR_BG_RAM_WRITE_LOWER:		STRING "BG RAM WRITE (LOWER)"
STR_BG_RAM_WRITE_UPPER:		STRING "BG RAM WRITE (UPPER)"
STR_BG_RAM_WRITE_BOTH:		STRING "BG RAM WRITE (BOTH)"

STR_FG_RAM_ADDRESS:		STRING "FG RAM ADDRESS"
STR_FG_RAM_DATA_LOWER:		STRING "FG RAM DATA (LOWER)"
STR_FG_RAM_DATA_UPPER:		STRING "FG RAM DATA (UPPER)"
STR_FG_RAM_DATA_BOTH:		STRING "FG RAM DATA (BOTH)"
STR_FG_RAM_MARCH_LOWER:		STRING "FG RAM MARCH (LOWER)"
STR_FG_RAM_MARCH_UPPER:		STRING "FG RAM MARCH (UPPER)"
STR_FG_RAM_MARCH_BOTH:		STRING "FG RAM MARCH (BOTH)"
STR_FG_RAM_OUTPUT_LOWER:	STRING "FG RAM DEAD OUTPUT (LOWER)"
STR_FG_RAM_OUTPUT_UPPER:	STRING "FG RAM DEAD OUTPUT (UPPER)"
STR_FG_RAM_OUTPUT_BOTH:		STRING "FG RAM DEAD OUTPUT (BOTH)"
STR_FG_RAM_WRITE_LOWER:		STRING "FG RAM WRITE (LOWER)"
STR_FG_RAM_WRITE_UPPER:		STRING "FG RAM WRITE (UPPER)"
STR_FG_RAM_WRITE_BOTH:		STRING "FG RAM WRITE (BOTH)"

STR_PALETTE_RAM_ADDRESS:	STRING "PALETTE RAM ADDRESS"
STR_PALETTE_RAM_DATA_LOWER:	STRING "PALETTE RAM DATA (LOWER)"
STR_PALETTE_RAM_DATA_UPPER:	STRING "PALETTE RAM DATA (UPPER)"
STR_PALETTE_RAM_DATA_BOTH:	STRING "PALETTE RAM DATA (BOTH)"
STR_PALETTE_RAM_MARCH_LOWER:	STRING "PALETTE RAM MARCH (LOWER)"
STR_PALETTE_RAM_MARCH_UPPER:	STRING "PALETTE RAM MARCH (UPPER)"
STR_PALETTE_RAM_MARCH_BOTH:	STRING "PALETTE RAM MARCH (BOTH)"
STR_PALETTE_RAM_OUTPUT_LOWER:	STRING "PALETTE RAM DEAD OUTPUT (LOWER)"
STR_PALETTE_RAM_OUTPUT_UPPER:	STRING "PALETTE RAM DEAD OUTPUT (UPPER)"
STR_PALETTE_RAM_OUTPUT_BOTH:	STRING "PALETTE RAM DEAD OUTPUT (BOTH)"
STR_PALETTE_RAM_WRITE_LOWER:	STRING "PALETTE RAM WRITE (LOWER)"
STR_PALETTE_RAM_WRITE_UPPER:	STRING "PALETTE RAM WRITE (UPPER)"
STR_PALETTE_RAM_WRITE_BOTH:	STRING "PALETTE RAM WRITE (BOTH)"

STR_SPRITE_RAM_ADDRESS:		STRING "SPRITE RAM ADDRESS"
STR_SPRITE_RAM_DATA_LOWER:	STRING "SPRITE RAM DATA (LOWER)"
STR_SPRITE_RAM_DATA_UPPER:	STRING "SPRITE RAM DATA (UPPER)"
STR_SPRITE_RAM_DATA_BOTH:	STRING "SPRITE RAM DATA (BOTH)"
STR_SPRITE_RAM_MARCH_LOWER:	STRING "SPRITE RAM MARCH (LOWER)"
STR_SPRITE_RAM_MARCH_UPPER:	STRING "SPRITE RAM MARCH (UPPER)"
STR_SPRITE_RAM_MARCH_BOTH:	STRING "SPRITE RAM MARCH (BOTH)"
STR_SPRITE_RAM_OUTPUT_LOWER:	STRING "SPRITE RAM DEAD OUTPUT (LOWER)"
STR_SPRITE_RAM_OUTPUT_UPPER:	STRING "SPRITE RAM DEAD OUTPUT (UPPER)"
STR_SPRITE_RAM_OUTPUT_BOTH:	STRING "SPRITE RAM DEAD OUTPUT (BOTH)"
STR_SPRITE_RAM_WRITE_LOWER:	STRING "SPRITE RAM WRITE (LOWER)"
STR_SPRITE_RAM_WRITE_UPPER:	STRING "SPRITE RAM WRITE (UPPER)"
STR_SPRITE_RAM_WRITE_BOTH:	STRING "SPRITE RAM WRITE (BOTH)"

STR_TXT_RAM_ADDRESS:		STRING "TXT RAM ADDRESS"
STR_TXT_RAM_DATA_LOWER:		STRING "TXT RAM DATA (LOWER)"
STR_TXT_RAM_DATA_UPPER:		STRING "TXT RAM DATA (UPPER)"
STR_TXT_RAM_DATA_BOTH:		STRING "TXT RAM DATA (BOTH)"
STR_TXT_RAM_MARCH_LOWER:	STRING "TXT RAM MARCH (LOWER)"
STR_TXT_RAM_MARCH_UPPER:	STRING "TXT RAM MARCH (UPPER)"
STR_TXT_RAM_MARCH_BOTH:		STRING "TXT RAM MARCH (BOTH)"
STR_TXT_RAM_OUTPUT_LOWER:	STRING "TXT RAM DEAD OUTPUT (LOWER)"
STR_TXT_RAM_OUTPUT_UPPER:	STRING "TXT RAM DEAD OUTPUT (UPPER)"
STR_TXT_RAM_OUTPUT_BOTH:	STRING "TXT RAM DEAD OUTPUT (BOTH)"
STR_TXT_RAM_WRITE_LOWER:	STRING "TXT RAM WRITE (LOWER)"
STR_TXT_RAM_WRITE_UPPER:	STRING "TXT RAM WRITE (UPPER)"
STR_TXT_RAM_WRITE_BOTH:		STRING "TXT RAM WRITE (BOTH)"

STR_WORK_RAM_ADDRESS:		STRING "WORK RAM ADDRESS"
STR_WORK_RAM_DATA_LOWER:	STRING "WORK RAM DATA (LOWER)"
STR_WORK_RAM_DATA_UPPER:	STRING "WORK RAM DATA (UPPER)"
STR_WORK_RAM_DATA_BOTH:		STRING "WORK RAM DATA (BOTH)"
STR_WORK_RAM_MARCH_LOWER:	STRING "WORK RAM MARCH (LOWER)"
STR_WORK_RAM_MARCH_UPPER:	STRING "WORK RAM MARCH (UPPER)"
STR_WORK_RAM_MARCH_BOTH:	STRING "WORK RAM MARCH (BOTH)"
STR_WORK_RAM_OUTPUT_LOWER:	STRING "WORK RAM DEAD OUTPUT (LOWER)"
STR_WORK_RAM_OUTPUT_UPPER:	STRING "WORK RAM DEAD OUTPUT (UPPER)"
STR_WORK_RAM_OUTPUT_BOTH:	STRING "WORK RAM DEAD OUTPUT (BOTH)"
STR_WORK_RAM_WRITE_LOWER:	STRING "WORK RAM WRITE (LOWER)"
STR_WORK_RAM_WRITE_UPPER:	STRING "WORK RAM WRITE (UPPER)"
STR_WORK_RAM_WRITE_BOTH:	STRING "WORK RAM WRITE (BOTH)"

STR_MAD_ROM_CRC32:		STRING "MAD ROM CRC32 ERROR"
STR_MAD_ROM_ADDRESS:		STRING "MAD ROM ADDRESS ERROR"
