all:
	make -f Makefile.mgakuen2
	make -f Makefile.pang
	make -f Makefile.pkladies
	make -f Makefile.qsangoku-hardware
	make -f Makefile.qsangoku-mame
	make -f Makefile.qtoto1-hardware
	make -f Makefile.qtono1-mame
	make -f Makefile.spang

clean:
	make -f Makefile.mgakuen2 clean
	make -f Makefile.pang clean
	make -f Makefile.pkladies clean
	make -f Makefile.qsangoku-hardware clean
	make -f Makefile.qsangoku-mame clean
	make -f Makefile.qtoto1-hardware clean
	make -f Makefile.qtono1-mame clean
	make -f Makefile.spang clean
