all:
	make -f Makefile.3wonders-cps_b_21_bt1
	make -f Makefile.captcomm-cps_b_21_bt3
	make -f Makefile.ghouls-cps_b_01
	make -f Makefile.mercs-cps_b_12
	make -f Makefile.sf2-cps_b_11
	make -f Makefile.sf2jf-cps_b_15

clean:
	make -f Makefile.3wonders-cps_b_21_bt1 clean
	make -f Makefile.captcomm-cps_b_21_bt3 clean
	make -f Makefile.ghouls-cps_b_01 clean
	make -f Makefile.mercs-cps_b_12 clean
	make -f Makefile.sf2-cps_b_11 clean
	make -f Makefile.sf2jf-cps_b_15 clean
