	include "cpu/68000/auto_test_handler.inc"
	include "cpu/68000/macros.inc"

	global AUTO_DSUB_TEST_TABLE
	global AUTO_FUNC_TEST_TABLE

	section data

AUTO_DSUB_TEST_TABLE:
	AUTO_TEST_ITEM auto_diag_rom_address_test_dsub, STR_TESTING_DIAG_ROM_ADDRESS
	AUTO_TEST_ITEM auto_diag_rom_crc32_test_dsub, STR_TESTING_DIAG_ROM_CRC32
	AUTO_TEST_ITEM auto_work_ram_tests_dsub, STR_TESTING_WORK_RAM
	AUTO_TEST_ITEM_NULL

AUTO_FUNC_TEST_TABLE:
	AUTO_TEST_ITEM_NULL

STR_TESTING_DIAG_ROM_ADDRESS:	STRING "TESTING DIAG ROM ADDRESS"
STR_TESTING_DIAG_ROM_CRC32:	STRING "TESTING DIAG ROM CRC32"
STR_TESTING_WORK_RAM:		STRING "TESTING WORK RAM"
