; last updated by gen-error-codes on 2026-01-19 @ 02:40 UTC
TILE_RAM_BASE_EC               equ $01
EC_TILE_RAM_ADDRESS            equ $01 ; 000001
EC_TILE_RAM_DATA               equ $02 ; 000010
EC_TILE_RAM_MARCH              equ $03 ; 000011
EC_TILE_RAM_OUTPUT             equ $04 ; 000100
EC_TILE_RAM_WRITE              equ $05 ; 000101

WORK_RAM_BASE_EC               equ $06
EC_WORK_RAM_ADDRESS            equ $06 ; 000110
EC_WORK_RAM_DATA               equ $07 ; 000111
EC_WORK_RAM_MARCH              equ $08 ; 001000
EC_WORK_RAM_OUTPUT             equ $09 ; 001001
EC_WORK_RAM_WRITE              equ $0a ; 001010
