	include "cpu/68000/macros.inc"
	include "cpu/68000/tests/auto.inc"

	global AUTO_DSUB_LIST
	global AUTO_FUNC_LIST

	section data

AUTO_DSUB_LIST:
	AUTO_ENTRY auto_diag_rom_address_test_dsub, STR_TESTING_DIAG_ROM_ADDRESS
	AUTO_ENTRY auto_diag_rom_crc32_test_dsub, STR_TESTING_DIAG_ROM_CRC32
	AUTO_ENTRY auto_work_ram_tests_dsub, STR_TESTING_WORK_RAM
	AUTO_LIST_END

AUTO_FUNC_LIST:
	AUTO_ENTRY auto_palette_ram_tests, STR_TESTING_PALETTE_RAM
	AUTO_ENTRY auto_palette_ext_ram_tests, STR_TESTING_PALETTE_EXT_RAM
	AUTO_ENTRY auto_sprite_ram_tests, STR_TESTING_SPRITE_RAM
	AUTO_ENTRY auto_tile1_ram_tests, STR_TESTING_TILE1_RAM
	AUTO_ENTRY auto_tile2_ram_tests, STR_TESTING_TILE2_RAM
	AUTO_ENTRY auto_tile3_ram_tests, STR_TESTING_TILE3_RAM
	AUTO_LIST_END

STR_TESTING_DIAG_ROM_ADDRESS:	STRING "TESTING DIAG ROM ADDRESS"
STR_TESTING_DIAG_ROM_CRC32:	STRING "TESTING DIAG ROM CRC32"
STR_TESTING_PALETTE_RAM:	STRING "TESTING PALETTE RAM"
STR_TESTING_PALETTE_EXT_RAM:	STRING "TESTING PALETTE EXT RAM"
STR_TESTING_SPRITE_RAM:		STRING "TESTING SPRITE RAM"
STR_TESTING_TILE1_RAM:		STRING "TESTING TILE1 RAM"
STR_TESTING_TILE2_RAM:		STRING "TESTING TILE2 RAM"
STR_TESTING_TILE3_RAM:		STRING "TESTING TILE3 RAM"
STR_TESTING_WORK_RAM:		STRING "TESTING WORK RAM"
