all:
	make -f Makefile.avengers-hardware
	make -f Makefile.avengers-mame
	make -f Makefile.trojan-hardware
	make -f Makefile.trojan-mame

clean:
	make -f Makefile.avengers-hardware clean
	make -f Makefile.avengers-mame clean
	make -f Makefile.trojan-hardware clean
	make -f Makefile.trojan-mame clean
