all:
	make -f Makefile.hardware
	make -f Makefile.hardware-27c010
	make -f Makefile.mame

clean:
	make -f Makefile.hardware clean
	make -f Makefile.hardware-27c010 clean
	make -f Makefile.mame clean

