REGB_BASE	equ $800140

	ifd _CPS_B_01_
		include "cps_b/cps_b_01.inc"
	endif

	ifd _CPS_B_02_
		include "cps_b/cps_b_02.inc"
	endif

	ifd _CPS_B_03_
		include "cps_b/cps_b_03.inc"
	endif

	ifd _CPS_B_04_
		include "cps_b/cps_b_04.inc"
	endif

	ifd _CPS_B_05_
		include "cps_b/cps_b_05.inc"
	endif

	ifd _CPS_B_11_
		include "cps_b/cps_b_11.inc"
	endif

	ifd _CPS_B_12_
		include "cps_b/cps_b_12.inc"
	endif

	ifd _CPS_B_13_
		include "cps_b/cps_b_13.inc"
	endif

	ifd _CPS_B_14_
		include "cps_b/cps_b_14.inc"
	endif

	ifd _CPS_B_15_
		include "cps_b/cps_b_15.inc"
	endif

	ifd _CPS_B_16_
		include "cps_b/cps_b_16.inc"
	endif

	ifd _CPS_B_17_
		include "cps_b/cps_b_17.inc"
	endif

	ifd _CPS_B_18_
		include "cps_b/cps_b_18.inc"
	endif

	ifd _CPS_B_21_BT1_
		include "cps_b/cps_b_21_bt1.inc"
	endif

	ifd _CPS_B_21_BT2_
		include "cps_b/cps_b_21_bt2.inc"
	endif

	ifd _CPS_B_21_BT3_
		include "cps_b/cps_b_21_bt3.inc"
	endif

	ifd _CPS_B_21_BT4_
		include "cps_b/cps_b_21_bt4.inc"
	endif

	ifd _CPS_B_21_BT5_
		include "cps_b/cps_b_21_bt5.inc"
	endif

	ifd _CPS_B_21_BT6_
		include "cps_b/cps_b_21_bt6.inc"
	endif

	ifd _CPS_B_21_BT7_
		include "cps_b/cps_b_21_bt7.inc"
	endif

	ifd _CPS_B_21_DEF_
		include "cps_b/cps_b_21_def.inc"
	endif

	ifd _CPS_B_21_QS1_
		include "cps_b/cps_b_21_qs1.inc"
	endif

	ifd _CPS_B_21_QS2_
		include "cps_b/cps_b_21_qs2.inc"
	endif

	ifd _CPS_B_21_QS3_
		include "cps_b/cps_b_21_qs3.inc"
	endif

	ifd _CPS_B_21_QS4_
		include "cps_b/cps_b_21_qs4.inc"
	endif

	ifd _CPS_B_21_QS5_
		include "cps_b/cps_b_21_qs5.inc"
	endif
